// SINH TỰ ĐỘNG — đừng sửa tay.
// Chạy `npm run menu:photos` sau khi thêm hoặc bớt ảnh trong public/images/menu/.
//
// Mỗi khoá là mã món trong menu.js, giá trị là đường dẫn ảnh. Món không có
// trong bảng này sẽ hiện ảnh mặc định menu-placeholder.svg.
export const menuImages = Object.freeze({
  'bac-xiu': '/images/menu/bac-xiu.webp',
  'banh-bo': '/images/menu/banh-bo.webp',
  'banh-bot-loc': '/images/menu/banh-bot-loc.webp',
  'banh-chuoi-hap': '/images/menu/banh-chuoi-hap.webp',
  'banh-chuoi-nuong': '/images/menu/banh-chuoi-nuong.webp',
  'banh-da-lon': '/images/menu/banh-da-lon.webp',
  'banh-mi-bo-la-lot': '/images/menu/banh-mi-bo-la-lot.webp',
  'banh-mi-ca-hop': '/images/menu/banh-mi-ca-hop.webp',
  'banh-mi-cha-ca': '/images/menu/banh-mi-cha-ca.webp',
  'banh-mi-heo-quay': '/images/menu/banh-mi-heo-quay.webp',
  'banh-mi-thit-nuong': '/images/menu/banh-mi-thit-nuong.webp',
  'banh-mi-trung': '/images/menu/banh-mi-trung.webp',
  'banh-tieu': '/images/menu/banh-tieu.webp',
  'bap-xao': '/images/menu/bap-xao.webp',
  'bo-kho': '/images/menu/bo-kho.webp',
  'bun-bo': '/images/menu/bun-bo.webp',
  'bun-mam-nem': '/images/menu/bun-mam-nem.webp',
  'bun-thit-nuong': '/images/menu/bun-thit-nuong.webp',
  'ca-phe-den': '/images/menu/ca-phe-den.webp',
  'ca-phe-sua': '/images/menu/ca-phe-sua.webp',
  'cam-ep': '/images/menu/cam-ep.webp',
  'canh-bun': '/images/menu/canh-bun.webp',
  'cari-ga': '/images/menu/cari-ga.webp',
  'chanh-day': '/images/menu/chanh-day.webp',
  'chanh-muoi': '/images/menu/chanh-muoi.webp',
  'com-chien-ca-man': '/images/menu/com-chien-ca-man.webp',
  'com-chien-duong-chau': '/images/menu/com-chien-duong-chau.webp',
  'com-ga': '/images/menu/com-ga.webp',
  'com-tam-trung': '/images/menu/com-tam-trung.webp',
  'da-chanh': '/images/menu/da-chanh.webp',
  'da-me': '/images/menu/da-me.webp',
  'dua-hau-ep': '/images/menu/dua-hau-ep.webp',
  'khoai-mi-nuong': '/images/menu/khoai-mi-nuong.webp',
  'khoai-mo-chien': '/images/menu/khoai-mo-chien.webp',
  'khoai-tay-chien': '/images/menu/khoai-tay-chien.webp',
  'la-han-qua': '/images/menu/la-han-qua.webp',
  'latte': '/images/menu/latte.webp',
  'mi-xao-bo': '/images/menu/mi-xao-bo.webp',
  'mi-xao-ga': '/images/menu/mi-xao-ga.webp',
  'mien-ga-trung-non': '/images/menu/mien-ga-trung-non.webp',
  'oi-ep': '/images/menu/oi-ep.webp',
  'pha-lau-long-bo': '/images/menu/pha-lau-long-bo.webp',
  'pho-bo': '/images/menu/pho-bo.webp',
  'pho-ga': '/images/menu/pho-ga.webp',
  'rau-ma-dau': '/images/menu/rau-ma-dau.webp',
  'rau-ma-dua': '/images/menu/rau-ma-dua.webp',
  'rau-ma-nguyen-chat': '/images/menu/rau-ma-nguyen-chat.webp',
  'sam-dua': '/images/menu/sam-dua.webp',
  'sinh-to-bo': '/images/menu/sinh-to-bo.webp',
  'sinh-to-chuoi-viet-quat': '/images/menu/sinh-to-chuoi-viet-quat.webp',
  'sinh-to-dau': '/images/menu/sinh-to-dau.webp',
  'sinh-to-mang-cau': '/images/menu/sinh-to-mang-cau.webp',
  'sinh-to-xoai': '/images/menu/sinh-to-xoai.webp',
  'suong-sam': '/images/menu/suong-sam.webp',
  'thom-ep': '/images/menu/thom-ep.webp',
  'tra-dao': '/images/menu/tra-dao.webp',
  'tra-nong': '/images/menu/tra-nong.webp',
  'tra-tac': '/images/menu/tra-tac.webp'
});
